post:
  tags:
    - Echo
  summary: Echo test
  description: This endpoint returns the exact message you've sent to it. You can use it for testing purposes.
  operationId: searchProductById
  parameters:
    - name: id
      in: path
      description: The ID of the product that you want to retrieve.
      example: 531
      required: true
      schema:
        type: integer
        format: int32
  security:
    - api_key: []
    - basic_auth: []
  responses:
    '200':
      description: OK
      headers:
        X-Rate-Limit:
          description: Calls per hour allowed by the user.
          schema:
            type: integer
            format: int32
        X-Expires-After:
          $ref: ../headers/ExpiresAfter.yaml
      content:
        application/json:
          schema:
            type: string
          examples:
            response:
              value: 'Hello world!'
        application/xml:
          schema:
            type: string
          examples:
            xml:
              value: '<response>Hello world in XML!</response>'
        text/csv:
          schema:
            type: string
    '400':
      description: Unauthorized
  requestBody:
    content:
      application/json:
        schema:
          type: string
          example: 'Hello world!'
      application/xml:
        schema:
          type: string
          example: 'Hello world in XML!'
    description: Example Echo payload. When the response is received, its contents should match the contents from the payload.
    required: true
